<?php

// Include Library classes
require_once(dirname(__FILE__) . '/../lib/BugHerd/Project.php');
require_once(dirname(__FILE__) . '/../lib/BugHerd/Task.php');
require_once(dirname(__FILE__) . '/../lib/BugHerd/User.php');
require_once(dirname(__FILE__) . '/../lib/BugHerd/Comment.php');
require_once(dirname(__FILE__) . '/../lib/BugHerd/Exception.php');
require_once(dirname(__FILE__) . '/../lib/BugHerd/Api.php');

/**
 * Test class for BugHerd_Project.
 * Generated by PHPUnit on 2012-05-10 at 20:03:50.
 */
class BugHerd_ExceptionTest extends PHPUnit_Framework_TestCase
{

  /**
   * @expectedException BugHerd_Exception
   */
  public function testException()
  {
    $api = new BugHerd_Api('fake_email', 'fake_password');
    $api->listUsers();
  }


}

