<?php

// Include Library classes
require_once(dirname(__FILE__) . '/../lib/BugHerd/Comment.php');

/**
 * Test class for BugHerd_Comment.
 * Generated by PHPUnit on 2012-05-10 at 20:03:50.
 */
class BugHerd_CommentTest extends PHPUnit_Framework_TestCase
{


  /**
   * @covers BugHerd_Comment::setId()
   * @covers BugHerd_Comment::getId()
   */
  public function testSetId() {
    $comment = new BugHerd_Comment();
    $comment->setId(5123);
    $id = $comment->getId();
    $this->assertEquals(5123, $id);
  }

  /**
   * @covers BugHerd_Comment::getText()
   * @covers BugHerd_Comment::setText()
   */
  public function testSetText() {
    $comment = new BugHerd_Comment();
    $comment->setText('text');
    $value = $comment->getText();
    $this->assertEquals('text', $value);
  }

  /**
   * @covers BugHerd_Comment::getUserId()
   * @covers BugHerd_Comment::setUserId()
   */
  public function testSetUserId() {
    $comment = new BugHerd_Comment();
    $comment->setUserId(5);
    $value = $comment->getUserId();
    $this->assertEquals(5, $value);
  }

  /**
   * @covers BugHerd_Comment::getCreated()
   * @covers BugHerd_Comment::setCreated()
   */
  public function testSetCreated() {
    $comment = new BugHerd_Comment();
    $date = new DateTime();
    $comment->setCreated($date);
    $value = $comment->getCreated();
    $this->assertEquals($date, $value);
  }

  /**
   * @covers BugHerd_Comment::getUpdated()
   * @covers BugHerd_Comment::setUpdated()
   */
  public function testSetUpdated() {
    $comment = new BugHerd_Comment();
    $date = new DateTime();
    $comment->setUpdated($date);
    $value = $comment->getUpdated();
    $this->assertEquals($date, $value);
  }

  /**
   * @covers BugHerd_Comment::toXml()
   */
  public function testToXml() {
    $xml = simplexml_load_string('<comment></comment>');
    $xml->addChild('text', 'text');
    $comment = new BugHerd_Comment();
    $comment->setText('text');
    $comment_xml = $comment->toXml();
    $this->assertXmlStringEqualsXmlString($xml->asXML(), $comment_xml);
  }

  /**
   * @covers BugHerd_Comment::fromXml()
   */
  public function testFromXml() {
    $xml = simplexml_load_string('<comment></comment>');
    $xml->addChild('id', 1234);
    $xml->addChild('text', 'text');
    $xml->addChild('user-id', 5);
    $xml = $xml->asXML();
    $comment = BugHerd_Comment::fromXml($xml);
    $this->assertEquals(1234, $comment->id);
    $this->assertEquals(5, $comment->user_id);
    $this->assertEquals('text', $comment->text);
  }
}

