<?php

// Include Library classes
require_once(dirname(__FILE__) . '/../lib/BugHerd/Project.php');

/**
 * Test class for BugHerd_Project.
 * Generated by PHPUnit on 2012-05-10 at 20:03:50.
 */
class BugHerd_ProjectTest extends PHPUnit_Framework_TestCase
{


  /**
   * @covers BugHerd_Project::setId()
   * @covers BugHerd_Project::getId()
   */
  public function testSetId() {
    $project = new BugHerd_Project();
    $project->setId(5123);
    $id = $project->getId();
    $this->assertEquals(5123, $id);
  }

  /**
   * @covers BugHerd_Project::getName()
   * @covers BugHerd_Project::setName()
   */
  public function testSetName() {
    $project = new BugHerd_Project();
    $project->setName('project name');
    $value = $project->getName();
    $this->assertEquals('project name', $value);
  }

  /**
   * @covers BugHerd_Project::getName()
   * @covers BugHerd_Project::setName()
   */
  public function testSetDevUrl() {
    $project = new BugHerd_Project();
    $project->setDevUrl('http://devurl.com');
    $value = $project->getDevUrl();
    $this->assertEquals('http://devurl.com', $value);
  }

  /**
   * @covers BugHerd_Project::getName()
   * @covers BugHerd_Project::setName()
   */
  public function testSetActive() {
    $project = new BugHerd_Project();
    $project->setActive(true);
    $value = $project->getActive();
    $this->assertTrue($value);
  }

  /**
   * @covers BugHerd_Project::getName()
   * @covers BugHerd_Project::setName()
   */
  public function testSetCreated() {
    $project = new BugHerd_Project();
    $date = new DateTime();
    $project->setCreated($date);
    $value = $project->getCreated();
    $this->assertEquals($date, $value);
  }

  /**
   * @covers BugHerd_Project::getName()
   * @covers BugHerd_Project::setName()
   */
  public function testSetUpdated() {
    $project = new BugHerd_Project();
    $date = new DateTime();
    $project->setUpdated($date);
    $value = $project->getUpdated();
    $this->assertEquals($date, $value);
  }

  /**
   * @covers BugHerd_Project::toXml()
   */
  public function testToXml() {
    $xml = simplexml_load_string('<project></project>');
    $xml->addChild('name', 'project name');
    $xml->addChild('devurl', 'http://devurl.com');
    $project = new BugHerd_Project();
    $project->setName('project name');
    $project->setDevUrl('http://devurl.com');
    $project_xml = $project->toXml();
    $this->assertXmlStringEqualsXmlString($xml->asXML(), $project_xml);
  }

  /**
   * @covers BugHerd_Project::fromXml()
   */
  public function testFromXml() {
    $xml = simplexml_load_string('<project></project>');
    $xml->addChild('id', 1234);
    $xml->addChild('name', 'project name');
    $xml->addChild('devurl', 'http://devurl.com');
    $xml = $xml->asXML();
    $project = BugHerd_Project::fromXml($xml);
    $this->assertEquals(1234, $project->id);
    $this->assertEquals('http://devurl.com', $project->devurl);
    $this->assertEquals('project name', $project->name);
  }
}

