<?php

// Include Library classes
require_once(dirname(__FILE__) . '/../lib/BugHerd/User.php');

/**
 * Test class for BugHerd_User.
 * Generated by PHPUnit on 2012-05-10 at 20:03:50.
 */
class BugHerd_UserTest extends PHPUnit_Framework_TestCase
{


  /**
   * @covers BugHerd_User::setId()
   * @covers BugHerd_User::getId()
   */
  public function testSetId() {
    $user = new BugHerd_User();
    $user->setId(5123);
    $id = $user->getId();
    $this->assertEquals(5123, $id);
  }

  /**
   * @covers BugHerd_User::getName()
   * @covers BugHerd_User::setName()
   */
  public function testSetName() {
    $user = new BugHerd_User();
    $user->setName('name');
    $value = $user->getName();
    $this->assertEquals('name', $value);
  }

  /**
   * @covers BugHerd_User::getSurName()
   * @covers BugHerd_User::setSurName()
   */
  public function testSetSurName() {
    $user = new BugHerd_User();
    $user->setSurName('lastname');
    $value = $user->getSurName();
    $this->assertEquals('lastname', $value);
  }

  /**
   * @covers BugHerd_User::getEmail()
   * @covers BugHerd_User::setEmail()
   */
  public function testSetEmail() {
    $user = new BugHerd_User();
    $user->setEmail('email@example.com');
    $value = $user->getEmail();
    $this->assertEquals('email@example.com', $value);
  }

  /**
   * @covers BugHerd_User::getCreated()
   * @covers BugHerd_User::setCreated()
   */
  public function testSetCreated() {
    $user = new BugHerd_User();
    $date = new DateTime();
    $user->setCreated($date);
    $value = $user->getCreated();
    $this->assertEquals($date, $value);
  }

  /**
   * @covers BugHerd_User::getUpdated()
   * @covers BugHerd_User::setUpdated()
   */
  public function testSetUpdated() {
    $user = new BugHerd_User();
    $date = new DateTime();
    $user->setUpdated($date);
    $value = $user->getUpdated();
    $this->assertEquals($date, $value);
  }

  /**
   * @covers BugHerd_User::toXml()
   */
  public function testToXml() {
    $xml = simplexml_load_string('<user></user>');
    $xml->addChild('name', 'name');
    $xml->addChild('surname', 'surname');
    $xml->addChild('email', 'email@example.com');
    $user = new BugHerd_User();
    $user->setName('name');
    $user->setSurName('surname');
    $user->setEmail('email@example.com');
    $user_xml = $user->toXml();
    $this->assertXmlStringEqualsXmlString($xml->asXML(),$user_xml);
  }

  /**
   * @covers BugHerd_User::fromXml()
   */
  public function testFromXml() {
    $xml = simplexml_load_string('<user></user>');
    $xml->addChild('id', 1234);
    $xml->addChild('name', 'name');
    $xml->addChild('surname', 'surname');
    $xml->addChild('email', 'email@example.com');
    $xml = $xml->asXML();
    $user = BugHerd_User::fromXml($xml);
    $this->assertEquals(1234, $user->id);
    $this->assertEquals('name', $user->name);
    $this->assertEquals('surname', $user->surname);
    $this->assertEquals('email@example.com', $user->email);
  }
}

